title: Kody Wildfeuer
description: AI agents, systems, and things I'm building.
url: "https://kody-w.github.io"
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
future: true
collections:
  twin_posts:
    output: true
    permalink: /digital-twin/:title/
  examples:
    output: true
    permalink: /learnwithkody/examples/:path/

defaults:
  - scope:
      path: ""
      type: examples
    values:
      layout: lwk_example
